### PR TITLE
Module definition fix

### PR DESCRIPTION
**Pull request by da7a90-backup**

### CODE REVIEW

**Comment by Morialkar** [comment]
@saibotsivad Can this get merged? This is making the module unusable due to typescript errors or API errors if using `cluster` instead of `dataSource`

**Comment by gagansuie** [comment]
Please merge this if everything looks good.

**Comment by saibotsivad** [comment]
@gagan-suie happy to work out a paid SLA if response time is important to you, my email is on my profile page.

**Review by bryanlatten — APPROVED** [review]
Very much needed

**Comment by saibotsivad** [comment]
Closed with https://github.com/saibotsivad/mongodb/releases/tag/v1.2.0

**Pull request closed without merging**
