### PR TITLE
Fix: changed the API endpoint to v1 after beta became obsolete

### PR DESCRIPTION
**Pull request by da7a90-backup**
this got me scratching my head for a very long time until I tested using Postman and went through the wrapper code that I noticed the API endpoint is still in beta. changed it to v1 now it's working again.

### CODE REVIEW

**Comment by saibotsivad** [comment]
Ah yeah, thanks for the note.

I hadn't noticed that the Data API moved out of beta, I'll go through and make sure this library is up to date, here in the next couple weeks.

For posterity / my own reference: a related issue was raised in [saibotsivad/mongodb-local-data-api#2](https://github.com/saibotsivad/mongodb-local-data-api/issues/2).

**Comment by saibotsivad** [comment]
Er, I mean, I'll look at the changes in this PR and make sure everything else is correct. (I use this in client apps, so I'll be able to verify everything is good.)

**Comment by da7a90-backup** [comment]
Super! I only changed the API endpoint url and changed "beta" to "v1" and it worked perfectly.

**Comment by da7a90-backup** [comment]
@saibotsivad Have you had time to check the changes in this PR to merge? I'm using this in a current client's project and want it to be working after an npm i .

**Comment by saibotsivad** [comment]
I haven't had time to release it, no. Hopefully this week, but I'm pretty busy with client work as well.

---

One thing I'd suggest, when working with client projects and a dependency isn't updating very fast (like here), is to fork it, make the PR etc, then when you do `npm install` simply reference your own fork+branch or fork+commit. In your case that would simply be:

```bash
npm install da7a90-backup/mongodb#main
```

Then, you can go about doing your normal work, and whenever the PR is merged and it's convenient to your workflow, you can go back and tidy things up.

I actually do that in this repo [(see the `package.json` file)](https://github.com/saibotsivad/mongodb/blob/77b142399e8f42047a28ab72def70304e686b3f6/package.json#L48) for [bundt](https://github.com/lukeed/bundt): Luke can't update the `terser` dependency without losing backward compatibility for legacy NodeJS versions, but he's not willing to do that yet. So I made my own fork, with `terser` updated, and every so often (every few months) I go back and see if I can switch back to his version yet.

Obviously this isn't ideal, but it seems to strike a good balance of contributing back to open source software that I use, and being able to push forward on client work in a timely manner.

**Comment by saibotsivad** [comment]
@da7a90-backup I did some other misc. tasks while updating this, see #2 for details.

Thanks again!

**Pull request closed without merging**
