### PR TITLE
MongoDB Data API is out of beta

### PR DESCRIPTION
**Pull request by saibotsivad**
Thanks to the note in #1 from @da7a90-backup I was informed that v1 is out.

With that, I'll update this library to v1 as well! 🎉

The breaking change is basically just on the init side, but also note that the Data API v1 has more consistent responses (when it returns JSON it always sets `Content-Type: application/json` instead of sometimes `text/plain`).

### Added
- Full test suite (it's the demo code) that actually connects to a MongoDB Data API
  instance to verify that all requests are being made correctly. (Note to my future
  self: this is using a free version, which will likely be automatically spun down
  due to inactivity. I will need to go spin it back up for tests to pass.)
### Changed
- BREAKING: Simplified the interface a bit, by requiring the fully qualified URL instead of region
  and/or app ID. Here are the [MongoDB URL docs](https://www.mongodb.com/docs/atlas/api/data-api-resources/#base-url).
- BREAKING: Renamed `cluster` to `dataSource` to match their parameter names better.
- Change the default-vs-overrides a bit: you don't *need* to specify the `dataSource`, `database`,
  or `collection` properties at initialization. If you do, you can still specify them at
  the request to override the defaults.

# Migration

Anywhere you are instantiating `mongodb`, you will need to...

Change `cluster` to `dataSource`:

```diff
const db = mongodb({
	apiKey,
	apiUrl,
-	cluster,
+	dataSource,
	database,
	collection,
})
```

If you are using `apiId` / `apiRegion` you will need to construct the URL yourself:

```diff
const db = mongodb({
	apiKey,
-	apiId,
-	apiRegion,
+	apiUrl: 'https://data.mongodb-api.com/app/YOUR_ID/endpoint/data/v1',
	dataSource,
	database,
	collection,
})
```

(Look at the [MongoDB Data API docs](https://www.mongodb.com/docs/atlas/api/data-api-resources/#base-url) for additional guidance on URLs.)

### CODE REVIEW

**Comment by da7a90-backup** [comment]
Hi @saibotsivad I think you still need to update the module definition file index.d.ts because if you use typescript there compiler errors if you use apiUrl instead off app id and region

**Comment by da7a90-backup** [comment]
Sorry I meant dataSource instead of cluster in the type definition file it's still defined as cluster but in index.js the parameter that is taken is named datasource so that might create issues

**Comment by saibotsivad** [comment]
Ugh yes, I see that now, thanks for the heads up 🤦‍♂️ I'll fix it early next week.

**Comment by da7a90-backup** [comment]
I just created a PR for that #3 you can check it out

**Comment by Morialkar** [comment]
Can this get merged? This is making the module unusable due to typescript errors

**Pull request merged**
